### PR TITLE
Update learn more domain from trailblazerb.org to trailblazer.to

### PR DESCRIPTION
**Pull request by wildjcrt**
Update link domain in lib/representable/deprecations.rb.

Old link: http://trailblazerb.org/gems/representable/upgrading-guide.html
New link: http://trailblazer.to/gems/representable/upgrading-guide.html

### CODE REVIEW

**Comment by apotonick** [comment]
There _should_ be a redirect from the old to the new domain....?!?!

**Comment by wildjcrt** [comment]
Don't know. 
http://trailblazerb.org/ returns ERR_NAME_NOT_RESOLVED.

**Comment by apotonick** [comment]
You have to send PRs against the `hermosa` branch!

**Comment by wildjcrt** [comment]
Excuse me. Where is the `hermosa` branch? I can't find it…… :sweat:

**Pull request closed without merging**
